"""add new column to user table by adding profile photo

Revision ID: 6b6d731d4208
Revises: b7dac47dbd6a
Create Date: 2023-04-06 03:11:56.860188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6d731d4208'
down_revision = 'b7dac47dbd6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
