"""add new column to user table

Revision ID: b7dac47dbd6a
Revises: ede5b14c532e
Create Date: 2023-04-06 03:09:11.845486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7dac47dbd6a'
down_revision = 'ede5b14c532e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=False),
                    sa.Column('role', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('quota', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('profile_image', sa.VARCHAR(length=200),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    sa.UniqueConstraint('email', name='users_email_key')
                    )
    op.create_table('tweets',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('source_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('source_name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('author', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('title', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('url', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('url_to_image', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('published_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('content', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='tweets_pkey'),
                    sa.UniqueConstraint('url', name='tweets_url_key')
                    )
    # ### end Alembic commands ###
