"""add new column to user table

Revision ID: ede5b14c532e
Revises: 3c3829cfadfa
Create Date: 2023-04-06 02:55:52.887383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ede5b14c532e'
down_revision = '3c3829cfadfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
